### ISSUE TITLE
tony-examples/README.md should be updated to use new `tony.application.security.enabled` property

### ISSUE THREAD

**Issue by erwa** [linkedin/TonY#16]
Currently, the README.md still mentions the old `tony.application.insecure-mode` property, which was changed to `tony.application.security.enabled` in https://github.com/linkedin/TonY/pull/14.

**Comment by oliverhu** [comment]
also the wiki pls

**Comment by erwa** [comment]
Ref: https://github.com/linkedin/TonY/wiki/TonY-Configurations still refers to `tony.application.insecure-mode` rather than `tony.application.security.enabled`

**Comment by oliverhu** [comment]
Resolved
