### ISSUE TITLE
TonyApplicationMaster should not set a default TonY history location

### ISSUE THREAD

**Issue by erwa** [linkedin/TonY#167]
Currently, we set the default TonY history location to `/path/to/tony-history`, which is not a very good default. Since this location needs to be coordinated between the client and the TonY history server, which will generally be on different machines, it's safer not to set it at all.

**Comment by erwa** [comment]
Hmm, I don't think this is fixed. I still see

`public static final String DEFAULT_TONY_HISTORY_LOCATION = "/path/to/tony-history";`

in TonyConfigurationKeys.java.

**Comment by oliverhu** [comment]
ok.. I saw there is a merged PR linked to this ticket, thought that fixed this.
