### ISSUE TITLE
Rename TensorFlowJob to TonyJob

### ISSUE THREAD

**Issue by erwa** [linkedin/TonY#173]
The Azkaban jobtype plugin for TonY is currently named TensorFlowJob. However, since TonY now supports running other frameworks such as PyTorch, a more generic name is in order. I suggest TonyJob (with a lowercase 'y' to match the naming convention of TonyApplicationMaster and TonyClient).

Internal Jira: LIHADOOP-43954

**Comment by oliverhu** [comment]
+1. Could you also update other non TensorFlow specific TensorFlowXXX convention to TonyXXX in the code base?
