### ISSUE TITLE
Expand TonY --src_dir to take multiple directories

### ISSUE THREAD

**Issue by oliverhu** [linkedin/TonY#180]
As part of Az on TonY initiative, it would be easier if we could support passing in multiple source directories to be localized to all machines.

**Comment by oliverhu** [comment]
Plan is to extend TonY's ClusterSubmitter to have another parameter of taking multiple directories, zip them, upload to HDFS and then append resources to tonyconf. Thought of adding this to TonyClient to expand, but I think `--resources` is generic enough.

**Comment by erwa** [comment]
What about adding a `--src_dirs` argument that accepts a comma-separated list of directories?

**Comment by oliverhu** [comment]
@erwa end goal is to deprecate --src_dirs in TonyClient and move this to submitter. --resources would be the only api for Tony client to accept resources.

Another thing I found useful to do is to add attributes to `--resources`:
--resources hdfs://abc/a.zip::archive,hdfs://def/g/::file (::file is optional), with this, we could leverage YARN to localize resources with cache.
