### ISSUE TITLE
TonyJob jobtype in Azkaban should use ClusterSubmitter rather than TonyClient

### ISSUE THREAD

**Issue by erwa** [linkedin/TonY#210]
The TonyJob Azkaban jobtype plugin currently directly calls TonyClient. However, for consistency with how TonY is generally launched from a gateway machine, it would be better for the TonyJob Azkaban jobtype to call ClusterSubmitter instead.

**Comment by oliverhu** [comment]
Let's also change the class name from TonyClient to Client in this change as this is incompatible anyway
