### ISSUE TITLE
Job stucking in GCP

### ISSUE THREAD

**Issue by xouyang0079** [linkedin/TonY#229]
I followed the instruction to submit the job in GCP, however the progress just stuck after a while, here is the console result:
![Untitled](https://user-images.githubusercontent.com/30067403/55296956-419e7d00-53e6-11e9-9787-120591535be9.png)

**Comment by xouyang0079** [comment]
after 23 mins, it shows failed.
![Untitled2](https://user-images.githubusercontent.com/30067403/55298161-bdea8d80-53f1-11e9-8e19-cfda9ffe6820.png)

**Comment by gogasca** [comment]
@xouyang0079 I was able to reproduce the issue:

Cluster creation:

```
export CLUSTER_NAME=tony-staging-3
export DATAPROC_VERSION=1.3-deb9
export ZONE=us-east1-b
export BUCKET=tony-staging

gcloud dataproc clusters create ${CLUSTER_NAME} --bucket ${BUCKET} \
--subnet default \
--zone $ZONE \
--master-machine-type n1-standard-4 --master-boot-disk-size 100 \
--num-workers 2 --worker-machine-type n1-standard-4 --worker-boot-disk-size 200 --image-version ${DATAPROC_VERSION} \
--initialization-actions gs://dataproc-initialization-actions/tony/tony.sh
```

Login via SSH to master:

```
cp /opt/tony//TonY/tony-cli/build/libs/tony-cli-0.3.0-all.jar /opt/tony/TonY-samples/
```
I will track Dataproc initialization to make sure it copies the latest CLI version automatically

Launching job:

```
export TONY_JARFILE="file:///opt/tony/TonY-samples/tony-cli-0.3.0-all.jar"

gcloud dataproc jobs submit hadoop --cluster "$CLUSTER_NAME" \
--class com.linkedin.tony.cli.ClusterSubmitter \
--jars "${TONY_JARFILE}" -- \
--src_dir=/opt/tony/TonY-samples/jobs/PTJob/src \
--task_params="--root gs://tony-staging/pytorch/jobs/pytorch" \
--conf_file=/opt/tony/TonY-samples/jobs/PTJob/tony.xml \
--executes mnist_distributed.py \
--python_venv=/opt/tony/TonY-samples/deps/pytorch.zip \
--python_binary_path=pytorch/bin/python3.5 &
```


As workaround used a previous Tony version during Cluster creation:

```--initialization-actions gs://tony-staging/tony_latest.sh```

And you can use the following CLI version:

```export TONY_JARFILE=gs://tony-staging/tony-cli-0.2.0-all.jar```

@oliverhu 

Container Logs:
[application_1554080258460_0001.log](https://github.com/linkedin/TonY/files/3027418/application_1554080258460_0001.log)

Stuck in:
```2019-04-01 01:13:45 INFO  ApplicationMaster:387 - Preparing application master..```

![image](https://user-images.githubusercontent.com/30065079/55298339-f2eee400-53e1-11e9-910f-5f5bc232576e.png)

**Comment by xouyang0079** [comment]
> @xouyang0079 I was able to reproduce the issue:
> 
> Cluster creation:
> 
> ```
> export CLUSTER_NAME=tony-staging-3
> export DATAPROC_VERSION=1.3-deb9
> export ZONE=us-east1-b
> export BUCKET=tony-staging
> 
> gcloud dataproc clusters create ${CLUSTER_NAME} --bucket ${BUCKET} \
> --subnet default \
> --zone $ZONE \
> --master-machine-type n1-standard-4 --master-boot-disk-size 100 \
> --num-workers 2 --worker-machine-type n1-standard-4 --worker-boot-disk-size 200 --image-version ${DATAPROC_VERSION} \
> --initialization-actions gs://dataproc-initialization-actions/tony/tony.sh
> ```
> Login via SSH to master:
> 
> ```
> cp /opt/tony//TonY/tony-cli/build/libs/tony-cli-0.3.0-all.jar /opt/tony/TonY-samples/
> ```
> I will track Dataproc initialization to make sure it copies the latest CLI version automatically
> 
> Launching job:
> 
> ```
> export TONY_JARFILE="file:///opt/tony/TonY-samples/tony-cli-0.3.0-all.jar"
> 
> gcloud dataproc jobs submit hadoop --cluster "$CLUSTER_NAME" \
> --class com.linkedin.tony.cli.ClusterSubmitter \
> --jars "${TONY_JARFILE}" -- \
> --src_dir=/opt/tony/TonY-samples/jobs/PTJob/src \
> --task_params="--root gs://tony-staging/pytorch/jobs/pytorch" \
> --conf_file=/opt/tony/TonY-samples/jobs/PTJob/tony.xml \
> --executes mnist_distributed.py \
> --python_venv=/opt/tony/TonY-samples/deps/pytorch.zip \
> --python_binary_path=pytorch/bin/python3.5 &
> ```
> As workaround used a previous Tony version during Cluster creation:
> 
> `--initialization-actions gs://tony-staging/tony_latest.sh`
> 
> And you can use the following CLI version:
> 
> `export TONY_JARFILE=gs://tony-staging/tony-cli-0.2.0-all.jar`
> 
> @oliverhu
> 
> Seems to be that TonY job is stuck in allocating resources.
> 
> Container Logs:
> [application_1554080258460_0001.log](https://github.com/linkedin/TonY/files/3027418/application_1554080258460_0001.log)
> 
> Stuck in:
> `2019-04-01 01:13:45 INFO ApplicationMaster:387 - Preparing application master..`
> 
> ![image](https://user-images.githubusercontent.com/30065079/55298339-f2eee400-53e1-11e9-910f-5f5bc232576e.png)
> 
> Application
> 
> ![image](https://user-images.githubusercontent.com/30065079/55298527-1bc3a900-53e3-11e9-8eee-a83a602e3cd9.png)

**Comment by xouyang0079** [comment]
> @xouyang0079 I was able to reproduce the issue:
> 
> Cluster creation:
> 
> ```
> export CLUSTER_NAME=tony-staging-3
> export DATAPROC_VERSION=1.3-deb9
> export ZONE=us-east1-b
> export BUCKET=tony-staging
> 
> gcloud dataproc clusters create ${CLUSTER_NAME} --bucket ${BUCKET} \
> --subnet default \
> --zone $ZONE \
> --master-machine-type n1-standard-4 --master-boot-disk-size 100 \
> --num-workers 2 --worker-machine-type n1-standard-4 --worker-boot-disk-size 200 --image-version ${DATAPROC_VERSION} \
> --initialization-actions gs://dataproc-initialization-actions/tony/tony.sh
> ```
> Login via SSH to master:
> 
> ```
> cp /opt/tony//TonY/tony-cli/build/libs/tony-cli-0.3.0-all.jar /opt/tony/TonY-samples/
> ```
> I will track Dataproc initialization to make sure it copies the latest CLI version automatically
> 
> Launching job:
> 
> ```
> export TONY_JARFILE="file:///opt/tony/TonY-samples/tony-cli-0.3.0-all.jar"
> 
> gcloud dataproc jobs submit hadoop --cluster "$CLUSTER_NAME" \
> --class com.linkedin.tony.cli.ClusterSubmitter \
> --jars "${TONY_JARFILE}" -- \
> --src_dir=/opt/tony/TonY-samples/jobs/PTJob/src \
> --task_params="--root gs://tony-staging/pytorch/jobs/pytorch" \
> --conf_file=/opt/tony/TonY-samples/jobs/PTJob/tony.xml \
> --executes mnist_distributed.py \
> --python_venv=/opt/tony/TonY-samples/deps/pytorch.zip \
> --python_binary_path=pytorch/bin/python3.5 &
> ```
> As workaround used a previous Tony version during Cluster creation:
> 
> `--initialization-actions gs://tony-staging/tony_latest.sh`
> 
> And you can use the following CLI version:
> 
> `export TONY_JARFILE=gs://tony-staging/tony-cli-0.2.0-all.jar`
> 
> @oliverhu
> 
> Seems to be that TonY job is stuck in allocating resources.
> 
> Container Logs:
> [application_1554080258460_0001.log](https://github.com/linkedin/TonY/files/3027418/application_1554080258460_0001.log)
> 
> Stuck in:
> `2019-04-01 01:13:45 INFO ApplicationMaster:387 - Preparing application master..`
> 
> ![image](https://user-images.githubusercontent.com/30065079/55298339-f2eee400-53e1-11e9-910f-5f5bc232576e.png)
> 
> Application
> 
> ![image](https://user-images.githubusercontent.com/30065079/55298527-1bc3a900-53e3-11e9-8eee-a83a602e3cd9.png)

Thank you so much for your reproduction, any idea to fix it?

**Comment by oliverhu** [comment]
@erwa it seems it has been broken since 806b15473b8f8f1256991febade2424a9650f669

**Comment by oliverhu** [comment]
@xouyang0079  could you try use this release first? https://github.com/linkedin/TonY/releases/download/v0.2.0/tony-cli-0.2.0-all.jarony-cli-0.2.0-all.jar

**Comment by erwa** [comment]
Hmm, this might be related to https://github.com/linkedin/TonY/commit/806b15473b8f8f1256991febade2424a9650f669 as @oliverhu mentioned. It's hard to debug as I can't reproduce in the LinkedIn environment. I'll dig in to this on GCP when I get a chance tonight or later this week.

**Comment by oliverhu** [comment]
checked: 
8e60e9f543e991e50f977b6612f45804df50f969 doesn’t work, 
30c4c42e6f81de18b959de17555a9a7bd0c90a29 works
66a04dbb85601166fc543b35fd7eb58c4fe2e5e1 doesn't work
806b15473b8f8f1256991febade2424a9650f669 doesn't work

**Comment by erwa** [comment]
It is indeed 806b154 that breaks TonY on GCP. If I build using the previous commit (https://github.com/linkedin/TonY/commit/e59fff720c1dce8b33aea82c22636ea87c561ffe), it works.

**Comment by erwa** [comment]
Found the problem. Apparently in addition to adding `core-site.xml` and `yarn-site.xml`, we also need to add `core-default.xml` and `yarn-default.xml`. Made the changes in https://github.com/linkedin/TonY/pull/230.

**Comment by xouyang0079** [comment]
> https://github.com/linkedin/TonY/releases/download/v0.2.0/tony-cli-0.2.0-all.jarony-cli-0.2.0-all.jar

@oliverhu Hi, I try to download the tony-cli-0.2.0-all.jar and I submit the job by the following code:

export TONY_JARFILE=tony-cli-0.2.0-all.jar
gcloud dataproc jobs submit hadoop --cluster "$CLUSTER_NAME" \
--class com.linkedin.tony.cli.ClusterSubmitter \
--jars file:///opt/tony/TonY-samples/"${TONY_JARFILE}" -- \
--src_dir=/opt/tony/TonY-samples/jobs/TFJob/src \
--task_params='--data_dir /tmp/ --working_dir /tmp/' \
--conf_file=/opt/tony/TonY-samples/jobs/TFJob/tony.xml \
--executes mnist_distributed.py \
--python_venv=/opt/tony/TonY-samples/deps/tf.zip \
--python_binary_path=tf/bin/python3.5

But I still got the error:
<img width="1280" alt="Screen Shot 2019-04-02 at 1 24 26 AM" src="https://user-images.githubusercontent.com/30067403/55380636-637f2900-54e6-11e9-8bde-2ed5f1163dcc.png">

**Comment by erwa** [comment]
Hi @xouyang0079 , the job has now launched properly and the ps and workers have started. You'll need to check the logs in the AM, ps, and workers to see why the application failed.

**Comment by oliverhu** [comment]
@gogasca ^ if have anything else to do to Anthony's comment like how to navigate using the worker x's log links.

**Comment by gogasca** [comment]
@xouyang0079 Which TF version are you using? 
The latest TonY version supports TensorFlow 1.13.1, so make sure your virtual environment is running that specific version.

Please go to the master node in Dataproc via SSH and run the following command:

```
yarn logs -applicationId application_1554077615500_0002
```
And share it with us.

**Comment by gogasca** [comment]
Using latest TonY version 0.3.1 should work now. I just tested it.
From your Cloud shell run the following:

Few observations:
1. Using latest TonY client version
2. Using latest Dataproc version 1.4
3. Replace BUCKET with your correct Google Cloud Storage Bucket name
4. New Dataproc version uses Python 3.6

```
export CLUSTER_NAME=tony-staging-1
export DATAPROC_VERSION=1.4-debian9
export ZONE=us-west1-a
export BUCKET=<YOUR_BUCKET_NAME>
 
gcloud beta dataproc clusters create ${CLUSTER_NAME} \
--zone $ZONE \
--master-machine-type n1-standard-4 --master-boot-disk-size 100 \
--num-workers 2 --worker-machine-type n1-standard-4 --worker-boot-disk-size 200 --image-version ${DATAPROC_VERSION} \
--initialization-actions gs://tony-staging/tony.sh \
--scopes https://www.googleapis.com/auth/cloud-platform

export TONY_JARFILE="gs://tony-staging/tony-cli-0.3.1-all.jar"
export TONY_CLASS="com.linkedin.tony.cli.ClusterSubmitter"

job_id="test1"
gcloud dataproc jobs submit hadoop --cluster "${CLUSTER_NAME}" \
	  --class "${TONY_CLASS}" \
	  --jars "${TONY_JARFILE}" -- \
	  --executes mnist_distributed.py \
	  --conf_file=/opt/tony/TonY-samples/jobs/TFJob/tony.xml \
	  --python_venv=/opt/tony/TonY-samples/deps/tf.zip \
	  --src_dir=/opt/tony/TonY-samples/jobs/TFJob/src \
	  --task_params="--data_dir gs://tony-staging/tensorflow/data --working_dir gs://"${BUCKET}"/tensorflow/jobs/"${job_id}"/model" \
	  --python_binary_path=tf/bin/python3.6
```

**Comment by erwa** [comment]
FYI, I've released tony 0.3.1 with a fix for this issue to Maven here: https://repo1.maven.org/maven2/com/linkedin/tony/tony-cli/0.3.1/. It should be searchable at https://search.maven.org/ in an hour or so.

**Comment by erwa** [comment]
0.3.1 is available on search.maven.org now: https://search.maven.org/remotecontent?filepath=com/linkedin/tony/tony-cli/0.3.1/tony-cli-0.3.1-all.jar

**Comment by xouyang0079** [comment]
@gogasca @erwa Hi, thanks so much for your help, now it works.
