### ISSUE TITLE
Dependency download failed during build

### ISSUE THREAD

**Issue by lighTQ** [linkedin/TonY#234]
Relying on the download failure when executing the build -x test command,

<=====--------> 38% EXECUTING [9m 45s]
> :tony-azkaban:findbugsMain > Resolve files of :tony-azkaban:findbugs > findbu

<=====--------> 38% EXECUTING [9m 45s]

> Task :tony-azkaban:extractIncludeTestProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':tony-azkaban:testCompile'.
> Could not download hadoop-yarn-server-resourcemanager.jar (org.apache.hadoop:hadoop-yarn-server-resourcemanager:2.6.0)
   > Could not get resource 'https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-yarn-server-resourcemanager/2.6.0/hadoop-yarn-server-resourcemanager-2.6.0.jar'.
      > Read timed out
> Could not download hadoop-yarn-server-applicationhistoryservice.jar (org.apache.hadoop:hadoop-yarn-server-applicationhistoryservice:2.6.0)
   > Could not get resource 'https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-yarn-server-applicationhistoryservice/2.6.0/hadoop-yarn-server-applicationhistoryservice-2.6.0.jar'.
      > Read timed out
> Could not download bsh.jar (org.beanshell:bsh:2.0b4)
   > Could not get resource 'https://repo.maven.apache.org/maven2/org/beanshell/bsh/2.0b4/bsh-2.0b4.jar'.
      > Read timed out
> Could not download paranamer.jar (com.thoughtworks.paranamer:paranamer:2.6)
   > Could not get resource 'https://repo.maven.apache.org/maven2/com/thoughtworks/paranamer/paranamer/2.6/paranamer-2.6.jar'.
      > Read timed out
> Could not download javax.servlet-api.jar (javax.servlet:javax.servlet-api:3.0.1)
   > Could not get resource 'https://repo.maven.apache.org/maven2/javax/servlet/javax.servlet-api/3.0.1/javax.servlet-api-3.0.1.jar'.
      > Read timed out
> Could not download grizzly-http.jar (org.glassfish.grizzly:grizzly-http:2.1.2)
   > Could not get resource 'https://repo.maven.apache.org/maven2/org/glassfish/grizzly/grizzly-http/2.1.2/grizzly-http-2.1.2.jar'.
      > Read timed out
> Could not download management-api.jar (org.glassfish.external:management-api:3.0.0-b012)
   > Could not get resource 'https://repo.maven.apache.org/maven2/org/glassfish/external/management-api/3.0.

**Comment by oliverhu** [comment]
Pretty sure it is your local gradle/network config issue, all those links are accessible.
