### ISSUE TITLE
Support Horovod in TonY

### ISSUE THREAD

**Issue by erwa** [linkedin/TonY#239]
Horovod uses OpenMPI for worker communication. The distributed tasks must be launched using `mpirun` from a single node in order for the MPI context to be set up properly (see [this SO post](https://stackoverflow.com/questions/11176653/running-openmpi-program-without-mpirun)). [mpich2-yarn](https://github.com/alibaba/mpich2-yarn) runs `mpirun` from the AM after generating an SSH key pair and setting up passwordless SSH to all the worker hosts. We will need to do something similar to support Horovod in TonY.

**Comment by oliverhu** [comment]
Assigned to @goyalankit for more investigation.

**Comment by zuston** [comment]
Any update on it ? 
Now TonY has supported Horovod ?
I can't find any doc and example.
@oliverhu @goyalankit

**Comment by oliverhu** [comment]
No, we ended up investing in TF 2 native distributed training strategy than supporting Horovod.

**Comment by zuston** [comment]
We are willing to support horovod on TonY, any ideas on it?
If OK, i will sumit extra issue/PR on it.

**Comment by oliverhu** [comment]
@zuston and I chatted offline :) Horovod now supports the gloo backend so we might not need to hack around ssh. @zuston will open a new issue to describe the plan. Thanks @zuston !
