### ISSUE TITLE
Checkstyle and FindBugs does not seem to run properly for tony-portal module

### ISSUE THREAD

**Issue by erwa** [linkedin/TonY#266]
The tony-portal module uses the Play plugin and puts Java source files in a different location than standard Java modules use. As a result, I think Checkstyle and FindBugs are not finding the source files and not scanning them. I see some unused imports and there are no complaints during `./gradlew check`.

**Comment by oliverhu** [comment]
also even if i use -x test in gradle, it still runs tests for tony-portal module for some reason

**Comment by erwa** [comment]
@oliverhu, that's because Play tests using the `testPlayBinary` task. You'd have to add `-x testPlayBinary`. You can see all the tasks by running `./gradlew :tony-portal:tasks --all`.

**Comment by oliverhu** [comment]
I see, that explains.
