### ISSUE TITLE
PyTorch support for Tensorboard 

### ISSUE THREAD

**Issue by gogasca** [linkedin/TonY#275]
PyTorch 1.1 announced recent support for TensorBoard.
Creating FR for TonY to add support for it via Unique URL + sample

https://pytorch.org/docs/stable/tensorboard.html
https://github.com/pytorch/pytorch/releases

**Comment by erwa** [comment]
It looks like this PyTorch TensorBoard support is just a library to log events in a format that TensorBoard understands. Running TensorBoard as part of your TonY job can be done the same way, relying on the `TB_PORT` environment variable TonY sets. I don't think any additional dev effort is required.
