### ISSUE TITLE
TonY should launch TensorBoard in separate container

### ISSUE THREAD

**Issue by erwa** [linkedin/TonY#32]
Currently, TonY allocates the TensorBoard port on the chief worker (worker 0) and expects the chief worker task to read in the port from the environment and launch the TensorBoard process. However, often, this can cause the chief worker to fail with OutOfMemoryExceptions. To help mitigate this, TonY should allocate a separate container just for running TensorBoard. This would be more similar to what's generally done when running TensorFlow on Kubernetes -- TensorBoard is started in a separate pod form the workers and parameters servers (see the `training.yaml` example [here](https://banzaicloud.com/blog/tensorflow-on-k8s/)).

**Comment by hungj** [comment]
@erwa this should be possible now. You can try specifying tony.chief.instances=1 and tony.chief.memory=8g or whatever you want.

**Comment by erwa** [comment]
That's awesome. I guess all the user needs to do is update their script to add a `if is_chief(): launch_tensorboard()`

**Comment by oliverhu** [comment]
supported by users' code
