### ISSUE TITLE
TensorFlow read files from HDFS with no retry

### ISSUE THREAD

**Issue by ChengbingLiu** [linkedin/TonY#339]
Lately, we have been using TonY to run TensorFlow training jobs on YARN. Most functions work quite well. But there is one annoying issue, maybe with TensorFlow, but I seek to hear from the TonY dev team.

Our training and testing data resides in an HDFS cluster whose NameNode is quite busy and has "connection timed out" issue several times a day. Normally this does not cause any problem since HDFS client will re-connect and succeed. However, with TensorFlow estimator and Dataset API, which uses libhdfs under the hood, seems quite sensitive to the short outage of NameNode (1~2 minutes).

The stderr in worker:

> hdfsOpenFile(/data/train_data/part-m-00007): FileSystem#open((Lorg/apache/hadoop/fs/Path;I)Lorg/apache/hadoop/fs/FSDataInputStream;) error:
> 
> java.net.ConnectException: Call From node100.some.domain/10.1.1.100 to namenode01-other-cluster.some.domain:8020 failed on connection exception: java.net.ConnectException: Connection timed out; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
> 	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:731)
> 	at org.apache.hadoop.ipc.Client.call(Client.java:1476)
> 	at org.apache.hadoop.ipc.Client.call(Client.java:1409)
> 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
> 	at com.sun.proxy.$Proxy10.getBlockLocations(Unknown Source)
> 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:256)
> 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:256)
> 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:104)
> 	at com.sun.proxy.$Proxy11.getBlockLocations(Unknown Source)
> 	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:1279)
> 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:1266)
> 	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:1254)
> 	at org.apache.hadoop.hdfs.DFSInputStream.fetchLocatedBlocksAndGetLastBlockLength(DFSInputStream.java:305)
> 	at org.apache.hadoop.hdfs.DFSInputStream.openInfo(DFSInputStream.java:271)
> 	at org.apache.hadoop.hdfs.DFSInputStream.<init>(DFSInputStream.java:263)
> 	at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1585)
> 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:326)
> 	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:322)
> 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
> 	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:322)
> Caused by: java.net.ConnectException: Connection timed out
> 	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
> 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
> 	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
> 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
> 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
> 	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:615)
> 	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:714)
> 	at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:376)
> 	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1525)
> 	at org.apache.hadoop.ipc.Client.call(Client.java:1448)
> 	... 21 more
> Traceback (most recent call last):
>   File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/Rec/scripts/train_deep_wide.py", line 362, in <module>
>     tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/Rec/scripts/train_deep_wide.py", line 236, in main
>     eval_spec)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 471, in train_and_evaluate
>     return executor.run()
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 638, in run
>     getattr(self, task_to_run)()
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 648, in run_worker
>     return self._start_distributed_training()
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 789, in _start_distributed_training
>     saving_listeners=saving_listeners)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 358, in train
>     loss = self._train_model(input_fn, hooks, saving_listeners)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1124, in _train_model
>     return self._train_model_default(input_fn, hooks, saving_listeners)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1158, in _train_model_default
>     saving_listeners)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1407, in _train_with_estimator_spec
>     _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 676, in run
>     run_metadata=run_metadata)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1171, in run
>     run_metadata=run_metadata)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1270, in run
>     raise six.reraise(*original_exc_info)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
>     return self._sess.run(*args, **kwargs)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1327, in run
>     run_metadata=run_metadata)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1091, in run
>     return self._sess.run(*args, **kwargs)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow/python/client/session.py", line 929, in run
>     run_metadata_ptr)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
>     run_metadata)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.UnknownError: hdfs://namenode01-other-cluster.some.domain/data/part-m-00007; Unknown error 255
> 	 [[node IteratorGetNext (defined at /data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/Rec/scripts/train_deep_wide.py:59) ]]
> 	 [[node gradients_1/wide_params/wide_weight/ConcatPartitions/concat_grad/tuple/control_dependency_6 (defined at Rec/model/deep_wide.py:390) ]]
> 
> Caused by op u'IteratorGetNext', defined at:
>   File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/Rec/scripts/train_deep_wide.py", line 362, in <module>
>     tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/Rec/scripts/train_deep_wide.py", line 236, in main
>     eval_spec)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 471, in train_and_evaluate
>     return executor.run()
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 638, in run
>     getattr(self, task_to_run)()
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 648, in run_worker
>     return self._start_distributed_training()
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 789, in _start_distributed_training
>     saving_listeners=saving_listeners)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 358, in train
>     loss = self._train_model(input_fn, hooks, saving_listeners)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1124, in _train_model
>     return self._train_model_default(input_fn, hooks, saving_listeners)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1151, in _train_model_default
>     input_fn, model_fn_lib.ModeKeys.TRAIN))
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 992, in _get_features_and_labels_from_input_fn
>     self._call_input_fn(input_fn, mode))
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1079, in _call_input_fn
>     return input_fn(**kwargs)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/Rec/scripts/train_deep_wide.py", line 227, in <lambda>
>     input_fn=lambda: input_fn(train_files, worker_num, task_index, 10000, epochs=FLAGS.epochs),
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/Rec/scripts/train_deep_wide.py", line 59, in input_fn
>     features, labels = iterator.get_next()
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 414, in get_next
>     output_shapes=self._structure._flat_shapes, name=name)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1685, in iterator_get_next
>     output_shapes=output_shapes, name=name)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
>     op_def=op_def)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
>     return func(*args, **kwargs)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
>     op_def=op_def)
>   File "/data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/venv/venv/lib64/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
>     self._traceback = tf_stack.extract_stack()
> 
> UnknownError (see above for traceback): hdfs://namenode01-other-cluster.some.domain/data/part-m-00007; Unknown error 255
> 	 [[node IteratorGetNext (defined at /data6/yarn/local/usercache/user1/appcache/application_1560485382501_17736/container_e01_1560485382501_17736_01_000011/Rec/scripts/train_deep_wide.py:59) ]]
> 	 [[node gradients_1/wide_params/wide_weight/ConcatPartitions/concat_grad/tuple/control_dependency_6 (defined at Rec/model/deep_wide.py:390) ]]

From the error log, it does not seem to retry connecting to NameNode. I would like to know if you have a solution to this, either with libhdfs, TensorFlow, or with TonY. Thank you!

**Comment by oliverhu** [comment]
I think it is due to your client's misconfiguration, make sure local HADOOP_CONF is pointing to the right directory.

**Comment by ChengbingLiu** [comment]
@oliverhu I checked environment variables of the launched python process:
CLASSPATH includes /etc/hadoop/conf
HADOOP_CONF_DIR=/etc/hadoop/conf
YARN_CONF_DIR=/etc/hadoop/conf

It should be OK, and normally I was able to access both local and remote HDFS cluster. The problem only occurs to me when the remote HDFS's NameNode is unstable.

TensorFlow worker's log suggests that no retry has been made. Maybe there is problem with the Hadoop log4j setting?

**Comment by oliverhu** [comment]
The retry is based on YARN rpc's configuration. it should be something in yarn-site.xml or yarn-default.xml

**Comment by erwa** [comment]
I believe the HDFS client should retry by default, and you should also be able to configure the retry policy. If your NameNode is unstable, this should affect all your HDFS clients, not just TonY TensorFlow jobs. You might also look into tuning and stabilizing your NameNode.

**Comment by ChengbingLiu** [comment]
Thanks @oliverhu and @erwa , I have finally solved it out. By setting dfs.client.retry.policy.enabled = true , the HDFS client will try to reconnect to the specified active NameNode of another cluster.

Reference: https://issues.apache.org/jira/browse/HDFS-4389

Btw, we have many clusters, each with HA setup, which is why active NameNode of other cluster is specified instead of the HA namespace. There are too many configuration items for all clusters and it is not feasible to keep configuration files up-to-date...
