### ISSUE TITLE
Exclude evaluator from cluster spec and include it in untracked.jobtypes

### ISSUE THREAD

**Issue by ChengbingLiu** [linkedin/TonY#344]
To fully support evaluator, two changes should be made:
1. evaluator should not be included in cluster spec 
2. evaluator should better be included in `untracked.jobtypes` by default, along with ps

**Comment by erwa** [comment]
Hi @ChengbingLiu,

I believe it should not cause problems to include evaluator in the cluster_spec. TF seems to just ignore keys it doesn't recognize. We want TonY to be flexible and allow users to launch auxiliary task types (e.g.: to host sidecar tables) and have them all included in the cluster_spec, which is a central place all tasks can be parsed from.

As discussed in #345, in general you *do* want to wait for the evaluator to finish (to do a final evaluation after the workers have finished training). You should specify a max steps that is used by both the workers and evaluator to ensure the evaluator terminates. We have seen issues where user specified both num_epochs and max_steps, and num_epochs was reached before max_steps, and evaluator just waited forever. By only relying on max_steps, you can avoid this issue.

Of course, for your use case, if you want, you can always add evaluator to the untracked.jobtypes in your job config.
