### ISSUE TITLE
Unset MALLOC_ARENA_MAX for better performance

### ISSUE THREAD

**Issue by ChengbingLiu** [linkedin/TonY#346]
Hadoop set the environment variable `MALLOC_ARENA_MAX=4` by default, to limit virtual memory usage from increasing too fast (https://issues.apache.org/jira/browse/HADOOP-7154 ). Our experiments shows that removing this env can speed up 3x with TensorFlow training. If you see a long `Unique` bar in your timeline, then you are hitting this problem.

I propose to explicitly unset MALLOC_ARENA_MAX, or if you feel inpropriate, to provide a option to unset it.

**Comment by oliverhu** [comment]
Agree with this since GPU training requires access to the whole memory region, feel free to submit a PR on this.

**Comment by erwa** [comment]
We've seen cases where 300+ GB of virtual memory are used when only 3 GB of physical memory is used. This seems to happen when GPUs are used and the GPU allocates a lot of virtual memory. We had to disable the virtual memory check (`yarn.nodemanager.vmem-check-enabled=false`) to work around this issue. Perhaps setting `MALLOC_ARENA_MAX` can help.

**Comment by erwa** [comment]
@ChengbingLiu, can you explain what you mean by
 
> If you see a long `Unique` bar in your timeline, then you are hitting this problem.

I am not sure what the "`Unique` bar" is or what timeline you are referring to.

**Comment by ChengbingLiu** [comment]
@erwa Yes, you are right. This post is about letting virtual memory usage increase faster.

Unique is an operator for finding unique elements in a 1-D tensor: https://www.tensorflow.org/api_docs/python/tf/unique
![图片](https://user-images.githubusercontent.com/5031567/61097190-e2dcab00-a48c-11e9-9e38-c16d855acaea.png)

**Comment by burgerkingeater** [comment]
@ChengbingLiu `Our experiments shows that removing this env can speed up 3x with TensorFlow training`, can you share more context on this? Were you using GPUs, which tensorflow version you were using? Did the job read data from HDFS? It would be better if you care share the TF code.

The reason we circle back on this is we have seen VM increases 3X if we don't have this option enabled. But since our YARN cluster has VM restriction, and the process will be killed by YARN if VM usage is beyond threshold.

**Comment by ChengbingLiu** [comment]
@burgerkingeater `MALLOC_ARENA_MAX` is used by glibc for controlling the number of arenas.
More infomation:
https://www.gnu.org/software/libc/manual/html_node/Memory-Allocation-Tunables.html
https://devcenter.heroku.com/articles/tuning-glibc-memory-behavior

Our test environment was Wide and Deep model with CPUs, TF 1.13.1 (I don't think TF version is relevant though).

From the timeline in my previous post, you can find the unique operator has a relatively high cost. Unsetting this env can significantly increase the performance of allocating memory, thus reduces the total training time. A known side-effect is VMEM increasing faster, but that should not be a problem since YARN use a default vmem-pmem-ratio of 2.1.

**Comment by burgerkingeater** [comment]
@ChengbingLiu  when unsetting this, VM grows more than we would imagine and the 2.1 ratio is not sufficient. 
here is what we have seen:
“is running beyond virtual memory limits. Current usage: 2.4 GB of 16 GB physical memory used; 50.9 GB of 33.6 GB virtual memory used. Killing container.”

**Comment by ChengbingLiu** [comment]
@burgerkingeater what is your glibc version?

**Comment by ChengbingLiu** [comment]
Try glibc >= 2.17-106 and see whether vmem still explodes.

Or you may just set yarn.nodemanager.vmem-check-enabled=false, or raise vmem-pmem-ratio significantly.
