### ISSUE TITLE
Improve temporary files handling

### ISSUE THREAD

**Issue by ChengbingLiu** [linkedin/TonY#364]
ClusterSubmitter will generate the following two temp files:
- tony_src.zip
- application_xxxxx_yyy-tony-final.xml

Currently we have two problems:
1. If we start multiple jobs at the same time, we have concurrent writing issue with tony_src.zip, which causes the jobs to fail. Maybe the file name should have a unique id, or the file be located in a directory with a unique id.
2. application_xxxxx_yyy-tony-final.xml will be left there even if the job has finished successfully. After a few days, there will be a lot of such files. It is better to have a cleanup mechanism.

**Comment by oliverhu** [comment]
yeah, this is a known issue, application_xx_yy was added to avoid the 1st issue.

We could add some deletion logic after the job has finished (either failed or succeeded), feel free to submit a PR.

There is one good thing about leaving the files there tho.. debugging is easier with them there.

**Comment by zuston** [comment]
Solved https://github.com/linkedin/TonY/pull/574
