### ISSUE TITLE
TonY fails to utilize > 2 Virtual GPUs on Tensorflow

### ISSUE THREAD

**Issue by jhomrocky** [linkedin/TonY#371]
Attempting to integrate TonY into an existing Hadoop cluster (Hadoop && Yarn 3.1.1).

Cluster:
4 nodes, no GPU (1 being ResourceManager)
4 nodes, all have a virtual GPU attached

Using the `mnist_distributed` example (same happens with `mnist_keras_distributed` and other TF examples), TonY will force the Parameter Server onto a GPU node, (usually) force the ApplicationMaster onto a GPU node, and then will hang if requesting more than 2 workers with the error:

`INFO  ApplicationMaster:840 - Received registrations from 2 tasks, awaiting registration from 1 tasks.`

That error is with `workers=2`. If I do `workers=3`, I will get:

`INFO  ApplicationMaster:840 - Received registrations from 2 tasks, awaiting registration from 2 tasks.`

**Comment by oliverhu** [comment]
this should not be the same, can you paste how you start your job and configurations?

**Comment by jhomrocky** [comment]
@oliverhu Sure. I can provide the command to start & `tony.xml` config file, anything else I can get tomorrow morning. I followed the Tensorflow example so the steps leading up to attempting to run a job are the same. I've also tried numerous other ways like with and without `sudo`, with `ps.instances` at 0, manually specifying the nodes in `mnist_distributed.py` in the `ClusterSpec`, and a few others.

Commands:):
`./gradlew :tony-cli:build`

```java -cp `hadoop classpath`:/TonY/tony-cli/build/libs/tony-cli-x.x.x-all.jar com.linkedin.tony.cli.ClusterSubmitter --python_venv=/TonY/test/venv.zip --src_dir=/TonY/tony-examples/mnist-tensorflow --executes=mnist_distributed.py --task_params="--steps 1000 --data_dir /tmp/data --working_dir /tmp/model" --conf_file=/TonY/test/tony-test.xml --python_binary_path=venv/bin/python3 ```

`tony.xml` (`tony-test.xml` in my case):
```<configuration>
  <property>
    <name>tony.worker.instances</name>
    <value>2</value>
  </property>
  <property>
    <name>tony.worker.memory</name>
    <value>8g</value>
  </property>
  <property>
    <name>tony.ps.instances</name>
    <value>1</value>
  </property>
  <property>
    <name>tony.application.security.enabled</name>
    <value>false</value>
  </property>
  <property>
    <name>tony.am.gpus</name>
    <value>0</value>
  </property>
  <property>
    <name>tony.ps.gpus</name>
    <value>0</value>
  </property>
  <property>
    <name>tony.worker.gpus</name>
    <value>1</value>
  </property>
</configuration>```

**Comment by oliverhu** [comment]
Can you upload a zip of all the logs, like amstdout, amstderr for AM & stdout, stderr for the workers?

From what you said, it seems like the communication between workers and AM could not be established.

**Comment by jhomrocky** [comment]
I can in the morning, thanks again!

**Comment by jhomrocky** [comment]
Sorry for taking so long. Had to make sure IPs were replaced and whatnot.

ZIP is attached

**Comment by jhomrocky** [comment]
Here you go, sorry for taking so long, had to make sure privacy was taken care of

[TonY logs.zip](https://github.com/linkedin/TonY/files/3636533/TonY.logs.zip)

**Comment by oliverhu** [comment]
@jhomrocky pretty sure it is because you don't enough resource in your cluster for your third worker..

**Comment by jhomrocky** [comment]
There is. Each node has 4 cores and 32gb of RAM. I can't even run it with workers at 2GB.

**Comment by oliverhu** [comment]
How many GPUs do you have?

**Comment by jhomrocky** [comment]
4 virtual GPUs, one on each Node. They all pull from one central GPU that is distributed via NVIDIA GRID. This may well be an issue with it being a Virtual GPU, but I wanted to cover all aspects.

**Comment by hungj** [comment]
@jhomrocky you're using capacity scheduler right? Could you also include a screenshot of your scheduler page with the queue dropdown fully expanded, after the two workers + PS + AM has been allocated and the third one is stuck? It'd be useful to see what resources the resource manager thinks is available/allocated.

**Comment by jhomrocky** [comment]
@hungj yes I am. It only shows 2 GPUs being used :/ Unless I am reading it wrong.

![Used_Resources](https://user-images.githubusercontent.com/32281331/65355575-3f142780-dbc0-11e9-8b73-2c014d74fd69.PNG)

**Comment by hungj** [comment]
Yeah. That's weird, everything looks OK from the screenshot. Perhaps you could also verify that the resource manager is receiving this third worker resource request? Then can you verify that container _000005 (for the third worker) has not been allocated on the RM side?

If RM is indeed receiving this request and not allocating it, it sounds like a cluster configuration issue, you may need to dig through the RM logs / enable some debug logging on the RM to determine why it's not being allocated. If it is being allocated and TonY is not ack-ing it, then it sounds like a TonY bug.

**Comment by jhomrocky** [comment]
I can check it out first thing Monday morning for sure.

**Comment by jhomrocky** [comment]
@hungj Good morning. I combed through logs set to debug this morning and it doesn't seem that the RM is getting a request for an _000005 container at all. It gets requests for 000001-000004 but not 000005.

I can provide logs if it will help. Still waiting to hear back from NVIDIA.

**Comment by oliverhu** [comment]
Yah, this appears to be an issue from the RM side, please check with Nvidia to see if anything is wrong with their Grid. Keep us posted.

**Comment by jhomrocky** [comment]
For sure! Thanks for the help.

**Comment by oliverhu** [comment]
closing this, let us know if you still see problems
