### ISSUE TITLE
Does tony support tensorflow 2.0 (such as tf.distribute.experimental.MultiWorkerMirroredStrategy)?

### ISSUE THREAD

**Issue by WeponX** [linkedin/TonY#410]
Does tony support tensorflow 2.0 (such as tf.distribute.experimental.MultiWorkerMirroredStrategy)?

**Comment by oliverhu** [comment]
yeah, that should be supported.

**Comment by WeponX** [comment]
Since I'm not familiar with tony and tf-2.0, is there any examples or tutorial based on tensorflow 2.0?

**Comment by oliverhu** [comment]
@WeponX we will have 1 sometime in Jan

**Comment by WeponX** [comment]
is there any process ?

**Comment by oliverhu** [comment]
@goyalankit @arde171  please help the read me after the tf 2 test

**Comment by cguegi** [comment]
@oliverhu, @goyalankit, @arde171 is there any update on this? Thank you!

**Comment by oliverhu** [comment]
it works out of box for us.. @cguegi

**Comment by cguegi** [comment]
@oliverhu could you provide a small running example? I try to adapt mnist_keras_distributed.py to run on TF 2.3.1, however, I run into several issues. Currently with grpc ps port allocation.

**Comment by oliverhu** [comment]
sure, we will update the example a bit

**Comment by oliverhu** [comment]
@cguegi  check this out ? https://github.com/linkedin/TonY/pull/482/files

**Comment by oliverhu** [comment]
closing this

**Comment by cguegi** [comment]
@oliverhu updated example works. Thanks a lot!
I've added below lines in order to run on GPU
  try:
    tf.config.experimental.set_memory_growth(physical_devices[0], True)
  except:
    # Invalid device or cannot modify virtual devices once initialized.
   pass

**Comment by oliverhu** [comment]
@cguegi  Nice! please submit a PR with those changes!

**Comment by cguegi** [comment]
@oliverhu PR submitted.
