### ISSUE TITLE
Add option to stop application on failure of certain job 

### ISSUE THREAD

**Issue by morenn520** [linkedin/TonY#412]
Only untracked jobs, and chief(or chief worker) failure, will cause the application to short circuit. 
But for some case, user want to fail fast when evaluator failed, for evaluator will export models.

So I think it should have some option to config which jobs will cause short circuit of application, which is different with this issue. #406

**Comment by ChengbingLiu** [comment]
#406 handles failure of untracked type of jobs by killing the application, which I believe may not be very appropriate.

"Untracked" means that the application can finish without having them exited, which is quite different from "should kill application on job failure". In fact, the relationship can be summarized as follows

Types | ps | chief | worker | evaluator
------ | --- | ---- | ------- | ---------
Untracked | YES | NO | NO | NO
Should kill app on failure | YES | YES | MAY | MAY

Based on these observations, I believe it is better to add an extra option for whether the application should be killed on failure of certain job types, which user can specify on a job basis.

**Comment by oliverhu** [comment]
Sorry for the late reply, it was holiday season. @ChengbingLiu  @morenn520 from the table provided, I don't see a case that if a job type is untracked, but we should not kill app on failure?

 types | ? 
--|----
 untracked | yes 
 should kill app on failure | no

**Comment by morenn520** [comment]
The table should be as follows:

Types | ps | chief | worker | evaluator
-- | -- | -- | -- | --
Tracked | NO| YES | YES | YES 
Untracked | YES | NO | NO | NO
Should kill app on failure | YES | YES | MAY | MAY

@oliverhu I don’t deny that application should be killed on failure of untracked jobtype. 

I think that application **might need to be killed on failure of some other tracked jobtype in addition to chief**.

This is why I think an extra option is required for whether the application should be killed on failure of certain job types

**Comment by oliverhu** [comment]
@morenn520 I believe after #406 whenever a job type fails, the whole application will shutdown. Before #406, it was only tracked jobs will cause application to short circuit.

Otherwise, there is a bug..

**Comment by ChengbingLiu** [comment]
@oliverhu If a job type is tracked, e.g. worker or evaluator, we may still want to kill app on job failure. Current implementation will only fail the application when chief or worker 0 failed:
https://github.com/linkedin/TonY/blob/0c4bd4095d21b2d1ebbf7441d59fe42022714464/tony-core/src/main/java/com/linkedin/tony/tensorflow/TonySession.java#L255

**Comment by morenn520** [comment]
@oliverhu After #406 , it was only chief and untracked jobs will cause application to short circuit, which can not solve our problem.

We may still want to kill app on evaluator(or worker) failure, and we cannot set evaluator(or worker) as untracked jobtypes.

**Comment by oliverhu** [comment]
@morenn520 @ChengbingLiu i see, this makes sense

**Comment by oliverhu** [comment]
merged PR
