### ISSUE TITLE
Enable TonY to upload container's model dir/files to HDFS

### ISSUE THREAD

**Issue by zuston** [linkedin/TonY#422]
Now TonY enable to  upload user-specified resources  using tony.X.resources config param.
Maybe we alse need to upload container's model dir/files to HDFS when using PyTorch which don't support reading and writing HDFS natively.

**Comment by oliverhu** [comment]
We have a py4j bridge before to interact with hdfs but later deleted. The logic to upload model files should be done via a python hdfs library. The container log is aggregated by NM to hdfs.

**Comment by zuston** [comment]
Do we need to implement a mechanism to upload output to HDFS by user-specified model output path?

I think it's neccessary. Users do not need to do upload operations in the code explicitly like PyTorch, which is convenient for testing and going online.

**Comment by zuston** [comment]
> We have a py4j bridge before to interact with hdfs but later deleted. The logic to upload model files should be done via a python hdfs library. The container log is aggregated by NM to hdfs.

Do we need to implement a mechanism to upload output to HDFS by user-specified model output path?

I think it's neccessary. Users do not need to do upload operations in the code explicitly like PyTorch, which is convenient for testing and going online.

**Comment by oliverhu** [comment]
Yes, you should, since different training frameworks would have different model output expectations. This should be implemented in the client level libraries.

You don’t need to implement this for PyTorch or some specific frameworks, just search for a python HDFS library, there are a ton of them.
