### ISSUE TITLE
Problem launching job

### ISSUE THREAD

**Issue by drr342** [linkedin/TonY#50]
Hello,
I am having the following issue when trying to launch a job:

java.lang.RuntimeException: Failed to get FS delegation token for default FS.
        at com.linkedin.tony.TonyClient.getTokens(TonyClient.java:555)
        at com.linkedin.tony.TonyClient.run(TonyClient.java:177)
        at com.linkedin.tony.TonyClient.start(TonyClient.java:716)
        at com.linkedin.tony.TonyClient.start(TonyClient.java:703)
        at com.linkedin.tony.cli.ClusterSubmitter.main(ClusterSubmitter.java:54)

I went to the code and I see a call to fs.getDelegationToken(tokenRenewer). However, I don't see such method in the API for FileSystem, so I am not sure what I should do next.
Thanks in advance for the help provided!

**Comment by oliverhu** [comment]
@drr342 if you look at https://github.com/linkedin/TonY/tree/master/tony-examples/mnist-tensorflow,

If you don't have security enabled in your cluster, you can disable security with 
```
<configuration>
  <property>
    <name>tony.application.security.enabled</name>
    <value>false</value>
  </property>
</configuration>
```

The getDelegationToken API does exist in https://github.com/apache/hadoop/blob/f069d38c8d3c0bfa91b70a60e4e556ec708fc411/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java#L606

**Comment by oliverhu** [comment]
Please reopen if you still see issues.
