### ISSUE TITLE
Support GANG and FCFS distributed mode

### ISSUE THREAD

**Issue by zuston** [linkedin/TonY#501]
### What?
Now TonY support TensorFlow/PyTorch distributed mode. This means that the task executors started from TonY AM will construct a training cluster for TF.
What is independent-task mode? It differs from above mode. For example, for TF, it will not inject the TF_CONFIG env in task executor. So in multiple task executors, so multiple TF jobs will run independently and not communicate with each other.

### Why?
In our scenario, users need to do batch offline inference. And user only do prediction when directly using the **estimator predict api** and restoring parameters for model from one checkpoint, it dont work and unnessary by using TonY distributed training. 
In fact, in order to solve the above problem that does not need to be distributed and communicated, the above independent-task mode can be useful.

**Comment by zuston** [comment]
Any ideas on it? @burgerkingeater @oliverhu 
If OK, i will submit PR ~

**Comment by oliverhu** [comment]
I guess you just need to hide TF_CONFIG in env?

**Comment by zuston** [comment]
Yes. In addition, there is no need to wait for all resources to be satisfied before starting. @oliverhu

**Comment by oliverhu** [comment]
I see, as far as it doesn't introduce any incompatibility, please go ahead! 🚀 

cc @hungj
