### ISSUE TITLE
Tensorflow evaluator should be removed from TF_CONFIG

### ISSUE THREAD

**Issue by zuston** [linkedin/TonY#506]
### What?
 Tensorflow evaluator config can be removed from TF_CONFIG

### Why?
 I run the Parameter Server Training (single-client, linked to [RFC](https://github.com/tensorflow/community/blob/master/rfcs/20200306-single-client-parameter-server.md)) task on TonY using TF2.4,  task stuck. I have submit the qustion to Tensorflow community, but seems no update on it([linked issue](https://github.com/tensorflow/tensorflow/issues/46169)).

How to solve it on TonY? I think we can remove the evaluator conf from the Worker/PS task executors env. Besides, the tensorflow document also declare evalutor is not a role of the TF cluster([linked doc](https://www.tensorflow.org/tutorials/distribute/parameter_server_training#cluster_setup)).

**PR**: https://github.com/linkedin/TonY/pull/512

**Comment by zuston** [comment]
@oliverhu Please check it. 
If OK, i will submit PR.
Thanks!

**Comment by oliverhu** [comment]
I don't think having evaluator in TF_CONFIG would cause the job to hang, do you have evidence for that?

**Comment by zuston** [comment]
When I remove evaluator conf from TF_CONFIG, task runs normally.

**Comment by oliverhu** [comment]
Is this new in TF 2.4? distributed PS worker strategy works well with evaluator in TF_CONFIG

**Comment by oliverhu** [comment]
btw, do you also need to remove from CLUSTER_SPEC, or just TF_CONFIG?

**Comment by zuston** [comment]
> When I remove evaluator conf from TF_CONFIG, task runs normally.
Sorry, I made a mistake and correct it that I just remove the evaluator conf from tony.xml, task runs normally.
removed eval conf like following.
```
<property>
  <name>tony.evaluator.instances</name>
  <value>2</value>
</property>
<property>
  <name>tony.evaluator.memory</name>
  <value>10g</value>
</property>
<property>
  <name>tony.evaluator.vcores</name>
  <value>2</value>
</property>
```


> Is this new in TF 2.4? distributed PS worker strategy works well with evaluator in TF_CONFIG
I think yes. Just encountering this problem in PS2.4 single-client PS

> btw, do you also need to remove from CLUSTER_SPEC, or just TF_CONFIG?
I will try it on TonY.

@oliverhu

**Comment by zuston** [comment]
Besides, traning task with TF2.4 PS strategy will not finish, because the TF worker will not stop, it waits the chief to diliver the task to it.
So how to do it in TonY? Now we should set the tony conf like following

```
<property>
  <name> tony.application.untracked.jobtypes</name>
  <value>ps,worker</value>
</property>
```

I think we should add documentation to explain how to use single-client ps strategy. After all, this strategy has changed a lot.

@oliverhu

**Comment by oliverhu** [comment]
interesting.. good to know. we can't change to untrack ps & worker by default now though since it would break compatibility. Feel free to open a PR to remove evaluator from TF_CONFIG, that sounds fine.

**Comment by zuston** [comment]
Sumit new [PR](https://github.com/linkedin/TonY/pull/515) for fixing evaluator error when in estimator multiworker strategy(TF1.14).

I'm sorry that the previous PR was not fully tested.
@oliverhu
