### ISSUE TITLE
Support multiple ml frameworks using generic interface 

### ISSUE THREAD

**Issue by zuston** [linkedin/TonY#526]
To support horovod on TonY, I came up with a new idea by using `MLFrameworkRuntime` to support different frameworks in a more efficient and simple way.

Actually. we should separate these change in another PR to ensure readability.

Refer to here: https://github.com/linkedin/TonY/pull/524#issuecomment-819107357

**Comment by zuston** [comment]
Any ideas? @oliverhu

**Comment by oliverhu** [comment]
I agree with this. We can split into possibly 3 PRs. 1 for this refactor, another 1 for creating new RPC endpoints, the last one to make it work Horovod?  @zuston

**Comment by zuston** [comment]
It’s fine. I will do it later. @oliverhu

**Comment by zuston** [comment]
Linked PR: https://github.com/linkedin/TonY/pull/529
