### ISSUE TITLE
Classpath of TonY libraries isn't forwarded to AM container launch

### ISSUE THREAD

**Issue by wobfan** [linkedin/TonY#531]
I am running the current TonY build 0.4.6 on my Ubuntu machine with a standalone YARN/Hadoop installation.
The Hadoop installation is working well, but when I try to run something with TonY I get the error `Error: Could not find or load main class com.linkedin.tony.ApplicationMaster` while launching the container.

I ran TonY with 
```
java -cp "$(hadoop classpath --glob):/home/wobbe/.bin/tony_test/proj/*" \
    com.linkedin.tony.cli.ClusterSubmitter -executes models/mnist_distributed.py \
    -task_params '--input-dir input --output_dir output' -src_dir src \
    -python_venv venv.zip -python_binary_path Python/bin/python \
    -conf tony.application.security.enabled=false
```
The TonY java libraries are located in the above mentioned classpath.

When I look into `launch_container.sh` from the userlogs I see that the following command is run: 
`exec /bin/bash -c "$JAVA_HOME/bin/java -Xmx1638m -Dyarn.app.container.log.dir=/home/wobbe/.bin/tony_test/hadoop/logs/userlogs/application_1618743980491_0004/container_1618743980491_0004_01_000001 com.linkedin.tony.ApplicationMaster`

It seems to me that the classpath of the TonY libs isn't forwarded from my initial java command to the launch of the AM container, which may be the reason why it doesn't find the ApplicationMaster class. Any suggestions would be much appreciated! Thanks :)

**Comment by oliverhu** [comment]
Take a look at https://github.com/linkedin/TonY/wiki/TonY-Configurations, you can set by using tony.containers.env

**Comment by wobfan** [comment]
Thanks for your reply!
I am a bit lost, I'm sorry for this.

Could you maybe suggest an example what env variable and how to set it to have the TonY jars used?
I tried
```
  <property>
    <name>tony.containers.envs</name>
    <value>CLASSPATH="/home/wobbe/.bin/tony_test/proj/*"</value>
  </property>
```
But I still get the same error unfortunately..

**Comment by wobfan** [comment]
Followup:
I edited `TonyClient.java` so that the environment variables for `CLASSPATH` including the above mentioned folder are hard-coded. After I added the folder containing the TonY jars, it failed because it didn't find the Hadoop classes, so I also included their jar libraries.
After that, it doesn't find the class `com.google.common.base.Preconditions`.

I am a newbie with gradle, but I guess there is a problem with setting the `CLASSPATH` to the gradle dependencies, or gradle fails to download them when building (which wouldn't make sense as the building process completes without errors).

I tested it on a Linux and a macOS system and the error is exactly the same, although I sticked to the guides in the README file. :-(

**Comment by oliverhu** [comment]
@wobfan did you use the fat jar ? the one like tony-cli-x.x-all.jar ? that should include all dependencies.

**Comment by wobfan** [comment]
I do not have a `tony-cli-0.4.6-all.jar`, but a `tony-cli-0.4.6-uber.jar`. Do you mean that, or is there supposed to be another one? 

I fact, when I use the uber one specifically, I do not get any ClassDefNotFound exceptions for TonY libraries any more, but still the ones for the hadoop libraries..

Thanks for your help!

**Comment by wobfan** [comment]
You were right, sorry I didn't think about that!

For everyone who encounters the same problem:
I needed to set the `HADOOP_HOME` env-variable in `hadoop/etc/hadoop/hadoop-env.sh` to the `hadoop` home-folder.

Thanks for your help! Appreciate it.
