### ISSUE TITLE
[Horovod-Runtime] Introduce custom horovod driver python script in debug mode

### ISSUE THREAD

**Issue by zuston** [linkedin/TonY#536]
### Why
For debug on production env or extend driver script, we need to introduce custom horovod driver python script in debug mode.

**Comment by zuston** [comment]
Any ideas on it? @oliverhu

**Comment by oliverhu** [comment]
why do you need a separate custom driver script just for debugging ?

**Comment by zuston** [comment]
Not limited to debugging. 
For example:
If Horovod is not compatible with our driver script, user can specify custom driver script to train temporarily, no need to wait TonY update

**Comment by oliverhu** [comment]
i see, pass a flag and we use that instead? (upload & localize similar to other resources)

**Comment by zuston** [comment]
Yes ~
