### ISSUE TITLE
Introduce pluggable runtime provider

### ISSUE THREAD

**Issue by zuston** [linkedin/TonY#537]
### Why
When we need to integrate a new framework, we need to support it in TonY. In fact, this is more difficult and time-consuming for newcomer developers. We should provide a way to dynamically specify different framework runtimes instead of being fixed in TonY code.

### How
I think we could do some changes as follows:
1. Allow user to specify framework type and framework runtime. like this
```xml
<property>
    <name>tony.pluggable.runtime</name>
    <value>
       tensorflow=com.linkedin.tony.runtime.TFRuntime,
       pytorch=com.linkedin.tony.runtime.PyTorchRuntime,
       ray=com.xxx.bigdata.RayRuntime
    </value>
  </property>
```
2. Provide a pluggable `RuntimeProvider`, which can be load corresponding framework's type runtime from external jar which can be found in current classpath

**Comment by zuston** [comment]
@oliverhu 
Any ideas on it?

**Comment by oliverhu** [comment]
Sounds good to me, what about we follow the YARN shuffle external jar format? config + manifest: https://hadoop.apache.org/docs/current/hadoop-mapreduce-client/hadoop-mapreduce-client-core/PluggableShuffleAndPluggableSort.html

**Comment by zuston** [comment]
I think using Java SPI will be better.
