### ISSUE TITLE
How can I provide my training data?

### ISSUE THREAD

**Issue by Adamage** [linkedin/TonY#550]
The documentation is pretty vague. Is it the "--input-dir"  ? How can I reference it inside submitted Python script, when for example the data is on HDFS ?

**Comment by oliverhu** [comment]
That is up to the user code. What TonY does is to get necessary resources from the cluster and launch your specified Python script.
Say you have a single machine TF script works locally like `./my_training.py --my_happy_input_dir hdfs://default/abc`. You just pass that to tony via `-executes ./my_training.py` and `-task_params   --my_happy_input_dir hdfs://default/abc`

**Comment by Adamage** [comment]
Ok thank you. So for example, when I create 10 workers on Yarn, how can I reference in the Python code, where the dataset is?

Suppose I upload the *mnist.npz* to hdfs://default/abc. Then in the training user code, should I use some kind of Python HDFS client to pull the data to the worker container? To load it into numpy ?

**Comment by Adamage** [comment]
Thank you, I think that clears it up.
