### ISSUE TITLE
Support tf.Estimator example

### ISSUE THREAD

**Issue by daugraph** [linkedin/TonY#559]
Thanks for your excellent work! 

As we all know, in TensorFlow, three types of APIs can be used to build models: tf.Session, tf.Keras,and tf.Estimator. TonY only contains tf.Session and tf.Keras example currently. However, tf.Estimator is also very popular among users. So it might be very helpful if TonY can support tf.Estimator example.

If possible, I will send a PR later.

**Comment by oliverhu** [comment]
It should be straightforward, please go ahead and create a PR, thanks!
