### ISSUE TITLE
tony-cli-all fat jar should exclude com/sun/jersey classes since they are CDDL licensed

### ISSUE THREAD

**Issue by erwa** [linkedin/TonY#56]
Hadoop transitively brings in jersey classes, which are CDDL-1.0-licensed. Since we do not use the CDDL 1.0 license, we should not be including the jersey classes in the tony-cli-all fat jar.

Ref: https://opensource.org/licenses/CDDL-1.0

**Comment by oliverhu** [comment]
Close with #70
