### ISSUE TITLE
Introduce timeout of container request

### ISSUE THREAD

**Issue by zuston** [linkedin/TonY#573]
The lack of Yarn GANG scheduler makes it deadlock when resources are tight.
So it's necessary to introduce timeout of container request to release resources.

**Comment by oliverhu** [comment]
The resource deadlock problem should be resolved in TF or YARN. I don't think it is the right place to solve it in TonY, maybe we can pivot to support elastic Horovod?

**Comment by zuston** [comment]
Elastic strategy on framework is the best solution to solve this problem. 
However when using current traditional training of static cluster topology, TonY will reserve some resources and wait the rest. This causes low resource utilization and possible deadlock. Hence container request timeout is also needed.
