### ISSUE TITLE
Set up continuous integration TonY repo

### ISSUE THREAD

**Issue by erwa** [linkedin/TonY#7]
Would be nice to set up continuous integration for this repo. Travis CI is the most popular tool, per https://blog.github.com/2017-11-07-github-welcomes-all-ci-tools/. It's free.

Would be good to run build on every Pull Request.

An admin of TonY project (@oliverhu or @chriseppstein) can set it up here: https://travis-ci.org/linkedin/TonY

**Comment by oliverhu** [comment]
Added and enforced that every PR must pass CI before can be merged.
