### ISSUE TITLE
Running this on Cloudera Hadoop Distribution (5.13.1)

### ISSUE THREAD

**Issue by mohammedayub44** [linkedin/TonY#78]
Hi,

I came across this great work just recently. I had lot of issues using the TensorflowOnSpark and TensorflowOnYARN earlier this year and had given up. I'm wondering how can I make use of this repo on top of my Cloudera Distribution of Hadoop. Any help is appreciated.

Thanks !

Mohammed Ayub

**Comment by zhe-thoughts** [comment]
Hi @mohammedayub44 , could you share details on previous errors trying TensorflowOnSpark and TensorflowOnYARN?

**Comment by mohammedayub44** [comment]
Hi @zhe-thoughts 
The issues were on creating TFRecords for Input and submitting jobs with yarn user https://github.com/yahoo/TensorFlowOnSpark/issues/293. 
However managed to replicate it successfully, also using TFoS requires you to make several changes to existing Tensorflow applications [Conversion Guide](https://github.com/yahoo/TensorFlowOnSpark/wiki/Conversion-Guide). 

I'm assuming this is something your repo would make it simpler to use it on distributed platforms.

Thanks.

Mohammed Ayub
