### ISSUE TITLE
TonyClient and startTHS.sh should read tony-site.xml config file from TONY_CONF_DIR

### ISSUE THREAD

**Issue by erwa** [linkedin/TonY#97]
TonY clients and the TonY History Server need to use the same value for the location of the history files. The client needs to tell the TonY AM to write to that location and the history server needs to read from that location.

We should define this location in a tony-site.xml file and expect it to be in the directory pointed to by the environment variable `TONY_CONF_DIR`, which can be set before running TonY clients or the history server.

See https://github.com/linkedin/TonY/pull/81#discussion_r234392784 for more context.

**Comment by pdtran3k6** [comment]
With that being said, my assumption would be that on both client host and history server host, there would be an environment variable `TONY_CONF_DIR` that points to a `tony-site.xml` with respect to that host. (The client host doesn't need other history config like keytab, principal, etc., but if that increases the maintenance overhead of `tony-site.xml`, then we could make them the same for now).
